const themes = {
	"bootstrap4-light-blue": "themes/bootstrap4-light-blue/theme.css",
	"bootstrap4-light-purple": "themes/bootstrap4-light-purple/theme.css",
	"bootstrap4-dark-blue": "themes/bootstrap4-dark-blue/theme.css",
	"bootstrap4-dark-purple": "themes/bootstrap4-dark-purple/theme.css",
	"md-light-indigo": "themes/md-light-indigo/theme.css",
	"md-light-deeppurple": "themes/md-light-deeppurple/theme.css",
	"md-dark-indigo": "themes/md-dark-indigo/theme.css",
	"md-dark-deeppurple": "themes/md-dark-deeppurple/theme.css",
	"mdc-light-indigo": "themes/mdc-light-indigo/theme.css",
	"mdc-light-deeppurple": "themes/mdc-light-deeppurple/theme.css",
	"mdc-dark-indigo": "themes/mdc-dark-indigo/theme.css",
	"mdc-dark-deeppurple": "themes/mdc-dark-deeppurple/theme.css",
	"tailwind-light": "themes/tailwind-light/theme.css",
	"fluent-light": "themes/fluent-light/theme.css",
	"lara-light-indigo": "themes/lara-light-indigo/theme.css",
	"lara-dark-indigo": "themes/lara-dark-indigo/theme.css",
	"lara-light-purple": "themes/lara-light-purple/theme.css",
	"lara-dark-purple": "themes/lara-dark-purple/theme.css",
	"lara-light-blue": "themes/lara-light-blue/theme.css",
	"lara-dark-blue": "themes/lara-dark-blue/theme.css",
	"lara-light-teal": "themes/lara-light-teal/theme.css",
	"lara-dark-teal": "themes/lara-dark-teal/theme.css",
	"saga-blue": "themes/saga-blue/theme.css",
	"saga-green": "themes/saga-green/theme.css",
	"saga-orange": "themes/saga-orange/theme.css",
	"saga-purple": "themes/saga-purple/theme.css",
	"vela-blue": "themes/vela-blue/theme.css",
	"vela-green": "themes/vela-green/theme.css",
	"vela-orange": "themes/vela-orange/theme.css",
	"vela-purple": "themes/vela-purple/theme.css",
	"arya-blue": "themes/arya-blue/theme.css",
	"arya-green": "themes/arya-green/theme.css",
	"arya-orange": "themes/arya-orange/theme.css",
	"arya-purple": "themes/arya-purple/theme.css",
	nova: "themes/nova/theme.css",
	"nova-alt": "themes/nova-alt/theme.css",
	"nova-accent": "themes/nova-accent/theme.css",
	"nova-vue": "themes/nova-vue/theme.css",
	"luna-amber": "themes/luna-amber/theme.css",
	"luna-blue": "themes/luna-blue/theme.css",
	"luna-green": "themes/luna-green/theme.css",
	"luna-pink": "themes/luna-pink/theme.css",
	rhea: "themes/rhea/theme.css",
};

type Keys = keyof typeof themes;

export { themes };
export type { Keys };
